coverage:
  range: 80..90
  round: up
  precision: 4
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
ignore:
  - "**/*Parser.cpp"
  - "Developer"
  - "Include"
  - "MSVC"
  - "Recorder/OutputType.cpp"
  - "Toolbox/amd-src"
  - "Toolbox/arpack-src"
  - "Toolbox/feast-src"
  - "Toolbox/lapack-ext"
  - "Toolbox/lis-src"
  - "Toolbox/metis-src"
  - "Toolbox/mumps-src"
  - "Toolbox/superlu-src"
  - "Toolbox/superlumt-src"
  - "Toolbox/argument.cpp"
  - "Toolbox/command.cpp"
  - "Toolbox/tester.pardiso.cpp"
