image: debian:latest
variables:
  DEBIAN_FRONTEND: noninteractive
stages:
  - build
build:
  stage: build
  tags:
    - watermill
    - hellfire
  before_script:
    - apt-get update && apt-get install -y build-essential cmake gfortran g++ git golang
  script:
    - go build Checker/updater.go
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --parallel $(nproc)
