if (BUILD_SHARED AND USE_MKL)
    if (MKLROOT MATCHES "(oneapi|oneAPI)")
        if (COMPILER_IDENTIFIER MATCHES "linux")
            if (USE_MPI)
                link_libraries(MKL::MKL_SCALAPACK MPI::MPI_C MPI::MPI_CXX MPI::MPI_Fortran)
            else ()
                link_libraries(MKL::MKL)
            endif ()
        elseif (COMPILER_IDENTIFIER MATCHES "win")
            link_libraries(mkl_rt)
            if (USE_MPI)
                link_libraries(MPI::MPI_C MPI::MPI_CXX MPI::MPI_Fortran)
            endif ()
        elseif (COMPILER_IDENTIFIER MATCHES "vs")
            if (USE_MPI)
                link_libraries(MKL::MKL_SCALAPACK MPI::MPI_C MPI::MPI_CXX MPI::MPI_Fortran)
            else ()
                link_libraries(MKL::MKL)
            endif ()
        endif ()
    endif ()
else ()
    if (NOT COMPILER_IDENTIFIER MATCHES "vs") # GCC OR CLANG COMPILER
        if (NOT USE_AOCL)
            find_library(HAS_QUADMATH quadmath)
            if (HAS_QUADMATH)
                link_libraries(quadmath)
            endif ()
            link_libraries(pthread gfortran openblas)
        else ()
            link_libraries(${AOCL_FLAME_PATH} ${AOCL_BLIS_PATH} ${AOCL_UTILS_PATH})
        endif ()
    else () # MSVC COMPILER
        if (USE_MPI)
            link_libraries(MKL::MKL_SCALAPACK)
        else ()
            link_libraries(libopenblas)
        endif ()
    endif ()
endif ()
