name: suanpan
base: core24
confinement: strict
contact: tlcfem@gmail.com
donation: https://ko-fi.com/suanpan
grade: stable
icon: Resource/suanPan-ua.svg
issues: https://github.com/TLCFEM/suanPan/issues
license: GPL-3.0
source-code: https://github.com/TLCFEM/suanPan
summary: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
version: "3.9.0"
website: https://bit.ly/suanpan-doc
description: |
  [**suanPan**](https://github.com/TLCFEM/suanPan) is a finite element method (FEM) simulation platform for applications
  in fields such as solid mechanics and civil/structural/seismic engineering. **suanPan** is written in modern high
  quality C++ code and is targeted to provide an efficient, concise, flexible and reliable FEM simulation platform.
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
apps:
  suanpan:
    command: bin/suanPan
    environment:
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
parts:
  suanpan:
    source: https://github.com/TLCFEM/suanPan.git
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=
      - -DSP_BUILD_PARALLEL=ON
      - -DSP_ENABLE_AVX2=OFF
      - -DSP_ENABLE_HDF5=ON
      - -DSP_ENABLE_IOMP=OFF
      - -DSP_ENABLE_MKL=ON
      - -DSP_ENABLE_SHARED_MKL=OFF
      - -DSP_ENABLE_VTK=ON
      - -DVTK_PATH=$CRAFT_PART_BUILD/lib/cmake/vtk-9.5/
    build-packages:
      - g++
      - gcc
      - gfortran
      - libglvnd-dev
      - wget
    override-build: |
      wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.5.0-linux.tar.gz
      tar xf VTK-9.5.0-linux.tar.gz
      wget -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/47c7d946-fca1-441a-b0df-b094e3f045ea/intel-onemkl-2025.2.0.629_offline.sh
      sh ./intel-onemkl-2025.2.0.629_offline.sh -a --silent --eula accept
      craftctl default
    stage-packages:
      - libgfortran5
      - libgomp1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
