name: suanpan
base: core18
version: "1.3"
summary: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
description: |
  [**suanPan**](https://tlcfem.github.io/suanPan/) is a finite element method (FEM) simulation platform for applications in fields such as solid mechanics and civil/structural/seismic engineering. The name **suanPan** (in some places such as suffix it is also abbreviated as **suPan**) comes from the term *Suan Pan* (算盤), which is [Chinese abacus](https://en.wikipedia.org/wiki/Suanpan). **suanPan** is written in modern high quality C++ code and is targeted to provide an efficient, concise, flexible and reliable FEM simulation platform.
grade: stable
confinement: strict
architectures:
  - build-on: amd64
apps:
  suanpan:
    command: bin/suanPan
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
parts:
  mkl:
    plugin: nil
    build-packages:
      - wget
      - cpio
    override-build: |
      wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
      sudo apt update && sudo apt install intel-oneapi-mkl-devel -y
      export MDEST=/build/suanpan/parts/suanpan/install/bin/
      mkdir -p $MDEST
      cp /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so $MDEST
      export MFROM=/opt/intel/oneapi/mkl/latest/lib/intel64/
      cp $MFROM/libmkl_core.so.1 $MDEST
      cp $MFROM/libmkl_intel_lp64.so.1 $MDEST
      cp $MFROM/libmkl_intel_thread.so.1 $MDEST
      cp $MFROM/libmkl_def.so.1 $MDEST
      cp $MFROM/libmkl_avx512.so.1 $MDEST
      cp $MFROM/libmkl_avx2.so.1 $MDEST
      cp $MFROM/libmkl_avx.so.1 $MDEST
  vtk:
    plugin: nil
    build-packages:
      - wget
      - cpio
      - cmake
      - gcc-8
      - g++-8
      - gfortran-8
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
    override-build: |
      wget https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
      tar xzf VTK-9.0.1.tar.gz && mkdir VTK-build && cd VTK-build
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/build/suanpan/parts/suanpan/VTK/ ../VTK-9.0.1
      make install -j4
  suanpan:
    after:
      - mkl
      - vtk
    source: https://github.com/TLCFEM/suanPan.git
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_MULTITHREAD=ON
      - -DUSE_HDF5=ON
      - -DUSE_EXTERNAL_VTK=ON
      - -DVTK_DIR=/build/suanpan/parts/suanpan/VTK/lib/cmake/vtk-9.0/
      - -DUSE_MKL=ON
      - -DMKLROOT=/opt/intel/oneapi/mkl/latest/
    build-environment:
      - CC: gcc-8
      - CXX: g++-8
      - FC: gfortran-8
    build-packages:
      - gcc-8
      - g++-8
      - gfortran-8
    stage-packages:
      - libgfortran5
      - libgomp1
      - libquadmath0
      - libglvnd0
      - libglx0
      - libopengl0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
