name: suanpan
base: core18
version: "1.6"
summary: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
description: |
  [**suanPan**](https://tlcfem.github.io/suanPan/) is a finite element method (FEM) simulation platform for applications in fields such as solid mechanics and civil/structural/seismic engineering. The name **suanPan** (in some places such as suffix it is also abbreviated as **suPan**) comes from the term *Suan Pan* (算盤), which is [Chinese abacus](https://en.wikipedia.org/wiki/Suanpan). **suanPan** is written in modern high quality C++ code and is targeted to provide an efficient, concise, flexible and reliable FEM simulation platform.
grade: stable
confinement: strict
architectures:
  - build-on: amd64
apps:
  suanpan:
    command: bin/suanPan
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
parts:
  mkl:
    plugin: nil
    build-packages:
      - wget
      - cpio
    override-build: |
      wget http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16533/l_mkl_2020.1.217.tgz
      tar xzf l_mkl_2020.1.217.tgz && cd l_mkl_2020.1.217
      sed -i 's/decline/accept/g' ./silent.cfg
      ./install.sh --silent ./silent.cfg
      export MDEST=/build/suanpan/parts/suanpan/install/bin/
      mkdir -p $MDEST
      export MFROM=/opt/intel/compilers_and_libraries/linux/lib/intel64/
      cp $MFROM/libiomp5.so $MDEST
      export MFROM=/opt/intel/mkl/lib/intel64/
      cp $MFROM/libmkl_core.so $MDEST
      cp $MFROM/libmkl_intel_lp64.so $MDEST
      cp $MFROM/libmkl_intel_thread.so $MDEST
      cp $MFROM/libmkl_def.so $MDEST
      cp $MFROM/libmkl_avx512.so $MDEST
      cp $MFROM/libmkl_avx2.so $MDEST
      cp $MFROM/libmkl_avx.so $MDEST
  vtk:
    plugin: nil
    build-packages:
      - wget
      - cpio
      - cmake
      - gcc-8
      - g++-8
      - gfortran-8
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
    override-build: |
      wget https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
      tar xzf VTK-9.0.1.tar.gz && mkdir VTK-build && cd VTK-build
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/build/suanpan/parts/suanpan/VTK/ ../VTK-9.0.1
      make install -j4
  suanpan:
    after:
      - mkl
      - vtk
    source: https://github.com/TLCFEM/suanPan.git
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_MULTITHREAD=ON
      - -DUSE_HDF5=ON
      - -DUSE_EXTERNAL_VTK=ON
      - -DVTK_DIR=/build/suanpan/parts/suanpan/VTK/lib/cmake/vtk-9.0/
      - -DUSE_MKL=ON
      - -DMKLROOT=/opt/intel/compilers_and_libraries/linux/mkl/
    build-environment:
      - CC: gcc-8
      - CXX: g++-8
      - FC: gfortran-8
    build-packages:
      - gcc-8
      - g++-8
      - gfortran-8
    stage-packages:
      - libgfortran5
      - libgomp1
      - libquadmath0
      - libglvnd0
      - libglx0
      - libopengl0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
