name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Feature
      placeholder: |
        Please provide a concise description of the requested feature and how it would be applied to practical problems.
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      placeholder: |
        Please provide any relevant references (papers, thesis, etc.).
        Please provide DOIs and links only to avoid copyright issues.
