jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - id: hashes
        name: Hash
        run: |
          CURRENT_SHA=$(git rev-parse HEAD)
          PARENT_SHA=$(git rev-parse HEAD~1)
          echo "current=$CURRENT_SHA" >> $GITHUB_OUTPUT
          echo "parent=$PARENT_SHA" >> $GITHUB_OUTPUT
      - continue-on-error: true
        name: Compare
        run: |
          echo "${{ secrets.STATIC_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no ${{ secrets.STATIC_HOST }}:~/Documents/fleet/hub/suanpan-results/Results-${{ steps.hashes.outputs.current }}.tar.gz results-current.tar.gz
          scp -i key.pem -o StrictHostKeyChecking=no ${{ secrets.STATIC_HOST }}:~/Documents/fleet/hub/suanpan-results/Results-${{ steps.hashes.outputs.parent }}.tar.gz results-parent.tar.gz
          rm -f key.pem
          python3 ./Script/compare.py results-current.tar.gz results-parent.tar.gz
name: A/B Testing
'on':
  workflow_call: null
  workflow_dispatch: null
