jobs:
  deployment:
    needs: guard
    runs-on: ubuntu-slim
    steps:
      - name: Delete Deployment
        uses: strumwolf/delete-deployment-environment@v4
        with:
          environment: github-pages
          token: ${{ secrets.ALL }}
  guard:
    if: github.repository == 'TLCFEM/suanPan'
    runs-on: ubuntu-slim
    steps:
      - run: echo "Hello, World!"
  package:
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
          owner_type: user
          package_name: suanpan
          token: ${{ secrets.ALL }}
          untagged_only: true
name: Delete
'on':
  workflow_call: null
  workflow_dispatch: null
