name: Delete Deployments
on:
  workflow_dispatch:
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete All
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.ALL }}
          environment: github-pages
