name: Daily
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
env:
  SP_TIME: ""
  ARTIFACT: ""
permissions:
  id-token: write
jobs:
  check-latest:
    runs-on: ubuntu-slim
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Commit
        id: commit
        run: |
          head=$(git ls-remote https://github.com/TLCFEM/suanPan.git HEAD | awk '{print $1}')
          echo "head=$head" >> $GITHUB_OUTPUT
          echo "$head" > .commit
      - name: Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: .commit
          key: commit-${{ steps.commit.outputs.head }}
  linux-daily:
    runs-on: ubuntu-24.04
    needs: check-latest
    if: needs.check-latest.outputs.cache-hit != 'true'
    timeout-minutes: 120
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Compile
        run: |
          sudo apt-get install patchelf lcov
          echo "SP_TIME=$(date +''%y%m%d'')" >> $GITHUB_ENV
          mkdir build && cd build
          cmake \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_INSTALL_PREFIX=dist \
          -DSP_ENABLE_ASAN=ON \
          -DSP_ENABLE_CODECOV=ON \
          -DSP_ENABLE_AVX2=OFF \
          ..
          cmake --build . --target install --config Debug -j $(nproc)
          cd ..
          ./Script/linux-patcher.sh ./build/dist/bin/suanPan
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-linux-debug-openblas-${{ env.SP_TIME }}.tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/build/dist/lib
          ./build/dist/bin/suanPan -v
      - name: Remote
        run: |
          echo "${{ secrets.STATIC_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no ${{ env.ARTIFACT }} ${{ secrets.STATIC_HOST }}:~/Documents/suanPan-daily/linux/
          rm -f key.pem
      - name: Coverage
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/build/dist/lib
          cd build
          bash ../Script/Coverage.sh .
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
  macos-daily:
    runs-on: ${{ matrix.os }}
    needs: check-latest
    if: needs.check-latest.outputs.cache-hit != 'true'
    timeout-minutes: 100
    strategy:
      matrix:
        os: [macos-14-large, macos-14-xlarge]
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Compile
        run: |
          echo "SP_TIME=$(date +''%y%m%d'')" >> $GITHUB_ENV
          brew install glfw glew libomp
          ./Script/mac-dependency.sh ${{ matrix.os }}
          mkdir build && cd build
          export CC=gcc-13 && export CXX=g++-13 && export FC=gfortran-13
          cmake \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_PREFIX_PATH="$(brew --prefix gcc@13)" \
          -DSP_ENABLE_AVX2=OFF \
          -DCMAKE_INSTALL_PREFIX=dist \
          ..
          cmake --build . --target install --config Debug -j 3
          cd ..
          ./Script/mac-patcher.sh build/dist
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-${{ matrix.os }}"
          file_name="${file_name//xlarge/arm64}"
          file_name="${file_name//large/amd64}"
          file_name+="-debug-gcc-${{ env.SP_TIME }}.tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
          ./build/dist/bin/suanPan -v
      - name: Remote
        run: |
          echo "${{ secrets.STATIC_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no ${{ env.ARTIFACT }} ${{ secrets.STATIC_HOST }}:~/Documents/suanPan-daily/macos/
          rm -f key.pem
  windows-gcc-daily:
    runs-on: windows-2025
    needs: check-latest
    if: needs.check-latest.outputs.cache-hit != 'true'
    timeout-minutes: 100
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: GCC
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.3.0posix-11.0.1-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
      - name: Compile
        run: |
          "SP_TIME=$(Get-Date -Format 'yyMMdd')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          mkdir build && cd build
          cmake -G "MinGW Makefiles" `
          -DCMAKE_BUILD_TYPE=Debug `
          -DCMAKE_C_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gcc.exe `
          -DCMAKE_CXX_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/g++.exe `
          -DCMAKE_Fortran_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gfortran.exe `
          -DCMAKE_INSTALL_PREFIX=dist `
          -DSP_ENABLE_AVX2=OFF `
          ..
          cmake --build . --target install --config Debug -j 4
      - name: Name
        shell: bash
        run: |
          echo "ARTIFACT=suanPan-win-gcc-debug-openblas-${{ env.SP_TIME }}.zip" >> "$GITHUB_ENV"
          ./Script/win-patcher.sh build/dist/bin/suanPan.exe
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          inputs: build/dist/bin/*.exe
      - name: Unsigned
        id: upload-unsigned-vs
        uses: actions/upload-artifact@v6
        with:
          name: unsigned-${{ env.ARTIFACT }}
          path: build/dist/bin/*.exe
      - name: Sign
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: "${{ secrets.SIGNPATH }}"
          organization-id: "b04bac88-d6e9-4140-948d-cb95e3095cbe"
          project-slug: "suanPan"
          signing-policy-slug: "test-signing"
          artifact-configuration-slug: "test"
          github-artifact-id: "${{ steps.upload-unsigned-vs.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: "build/dist/bin"
      - name: Test
        run: |
          cd build/dist/bin
          7z a -tzip ../../../${{ env.ARTIFACT }} ./*
          ./suanPan.exe -v
      - name: Remote
        shell: bash
        run: |
          echo "${{ secrets.STATIC_KEY }}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no ${{ env.ARTIFACT }} ${{ secrets.STATIC_HOST }}:~/Documents/suanPan-daily/windows/
          rm -f key.pem
