name: Daily
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
env:
  SP_TIME: ''
  ARTIFACT: ''
jobs:
  linux-daily:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        build: [ Debug ]
        compiler: [ { c: gcc, cpp: g++, fortran: gfortran } ]
        avx: [ OFF ]
        vtk: [ OFF ]
        mkl: [ OFF ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v5
        with:
          cache: false
      - name: Dependency
        run: |
          echo "SP_TIME=-$(date +''%y%m%d'')" >> $GITHUB_ENV
          sudo apt-get update && sudo apt-get install libglvnd-dev dpkg-dev xz-utils
      - name: Compile
        run: |
          go build Checker/updater.go
          mkdir build && cd build
          cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
          -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} \
          -DCMAKE_Fortran_COMPILER=${{ matrix.compiler.fortran }} \
          -DCMAKE_INSTALL_PREFIX=dist \
          -DSP_BUILD_PARALLEL=OFF \
          -DSP_ENABLE_AVX2=${{ matrix.avx }} \
          ..
          make install -j"$(nproc)" && make package
      - name: Pack
        run: |
          cp updater build/dist/bin
          file_name="linux-debug-openblas"
          file_name+="${{ env.SP_TIME }}.tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Test
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/build/dist/lib
          ./build/dist/bin/suanPan -v
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Remote
        uses: appleboy/scp-action@v1
        with:
          host: 170.64.176.26
          username: theodore
          key: ${{ secrets.VETERAN_KEY }}
          port: 2222
          source: ${{ env.ARTIFACT }}
          target: ~/Documents/suanPan-daily
