name: Develop
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  SP_TIME: ""
  ARTIFACT: ""
  IOMP: ""
  COVERAGE: ""
jobs:
  linux-dev:
    if: ${{ !contains(github.event.head_commit.message, '[skip.linux]') && !contains(github.event.head_commit.message, '[skip.all]') }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    timeout-minutes: 150
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        build: [Debug]
        compiler:
          [
            { c: gcc, cpp: g++, fortran: gfortran },
            { c: icx, cpp: icpx, fortran: ifx },
          ]
        avx: [OFF]
        vtk: [ON, OFF]
        mkl: [OFF]
        aocl: [ON, OFF]
        exclude:
          - compiler: { c: icx, cpp: icpx, fortran: ifx }
            mkl: OFF
          - compiler: { c: icx, cpp: icpx, fortran: ifx }
            aocl: ON
          - mkl: ON
            aocl: ON
          - os: ubuntu-24.04-arm
            compiler: { c: icx, cpp: icpx, fortran: ifx }
          - os: ubuntu-24.04-arm
            aocl: ON
          - os: ubuntu-24.04-arm
            mkl: ON
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: MKL
        run: |
          if [ "${{ matrix.mkl }}" == "ON" ] || [ "${{ matrix.compiler.c }}" == "icx" ]; then
            wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          fi
          sudo apt-get update
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            sudo apt-get install intel-oneapi-mkl-devel
          fi
          if [ "${{ matrix.compiler.c }}" == "icx" ]; then
            sudo apt-get install intel-oneapi-compiler-dpcpp-cpp intel-oneapi-compiler-fortran
            echo "IOMP=ON" >> "$GITHUB_ENV"
          else
            echo "IOMP=OFF" >> "$GITHUB_ENV"
          fi
      - name: Dependency
        run: |
          sudo apt-get install libglvnd-dev dpkg-dev xz-utils lcov patchelf
          if [[ "${{ matrix.build }}" == "Debug" ]] && [[ "${{ matrix.compiler.c }}" == "gcc" ]] && [[ "${{ matrix.avx }}" == "OFF" ]] && [[ "${{ matrix.vtk }}" == "OFF" ]]; then
            echo "COVERAGE=ON" >> "$GITHUB_ENV"
          else
            echo "COVERAGE=OFF" >> "$GITHUB_ENV"
          fi
      - name: Compile
        run: |
          if [ "${{ matrix.compiler.c }}" == "icx" ]; then
            source /opt/intel/oneapi/setvars.sh
          fi
          go build Checker/updater.go
          ./Script/linux-dependency.sh ${{ matrix.os }}
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
          -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} \
          -DCMAKE_Fortran_COMPILER=${{ matrix.compiler.fortran }} \
          -DCMAKE_INSTALL_PREFIX=build/dist \
          -DSP_BUILD_DLL_EXAMPLE=${{ env.COVERAGE }} \
          -DSP_BUILD_PARALLEL=$([[ "${{ matrix.build }}" == "Debug" ]] && echo "OFF" || echo "ON") \
          -DSP_ENABLE_AOCL=${{ matrix.aocl }} \
          -DSP_ENABLE_ASAN=$([[ "${{ env.COVERAGE }}" == "ON" && "${{ matrix.os }}" == *"arm"* ]] && echo "OFF" || echo "ON") \
          -DSP_ENABLE_AVX2=${{ matrix.avx }} \
          -DSP_ENABLE_CODECOV=${{ env.COVERAGE }} \
          -DSP_ENABLE_IOMP=${{ env.IOMP }} \
          -DSP_ENABLE_MKL=${{ matrix.mkl }} \
          -DSP_ENABLE_SHARED_MKL=OFF \
          -DSP_ENABLE_VTK=${{ matrix.vtk }} \
          -DVTK_PATH=/home/runner/work/suanPan/suanPan/VTK/lib/cmake/vtk-9.6/
          cmake --build build --target install --config ${{ matrix.build }} -j $(nproc)
          cmake --build build --target package
          ./Script/linux-patcher.sh ./build/dist/bin/suanPan
          cp updater build/dist/bin
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.3.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-linux"
          file_name+=$([[ "${{ matrix.os }}" != *"arm"* ]] && echo "-amd64" || echo "-arm64")
          file_name+=$([[ "${{ matrix.build }}" == "Debug" ]] && echo "-debug" || echo "-release")
          file_name+=$([[ "${{ matrix.compiler.c }}" == "gcc" ]] && echo "-gcc" || echo "-intel")
          if [[ "${{ matrix.os }}" != *"arm"* ]]; then
            file_name+=$([[ "${{ matrix.avx }}" == "ON" ]] && echo "-avx" || echo "-no-avx")
          fi
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            file_name+="-mkl"
          elif [ "${{ matrix.aocl }}" == "ON" ]; then
            file_name+="-aocl"
          else
            file_name+="-openblas"
          fi
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT }}
          path: build/dist
      - name: Test
        run: |
          ldd build/dist/bin/suanPan
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/build/dist/lib
          ./build/dist/bin/suanPan -v
      - name: Coverage
        if: env.COVERAGE == 'ON'
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/build/dist/lib
          cd build
          bash ../Script/Coverage.sh .
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
      - name: Result
        if: ${{ matrix.os == 'ubuntu-24.04' && env.COVERAGE == 'ON' && matrix.aocl == 'OFF' }}
        uses: actions/upload-artifact@v7
        with:
          name: Results-${{ hashFiles('./build/Results.tar.gz') }}
          path: ./build/Results.tar.gz
      - name: Report
        if: ${{ hashFiles('./build/coverage.info') != '' }}
        uses: codecov/codecov-action@v6
        with:
          plugins: gcov
          files: ./build/coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  linux-dev-mpi:
    if: ${{ !contains(github.event.head_commit.message, '[skip.linux]') && !contains(github.event.head_commit.message, '[skip.all]') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: Dependency
        run: |
          wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.1-${{ matrix.os }}.tar.gz
          tar xf VTK-9.6.1-${{ matrix.os }}.tar.gz
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mkl-devel intel-oneapi-mpi-devel libglvnd-dev dpkg-dev xz-utils lcov patchelf
      - name: Compile
        run: |
          source /opt/intel/oneapi/setvars.sh
          go build Checker/updater.go
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=build/dist \
          -DSP_BUILD_PARALLEL=ON \
          -DSP_ENABLE_64BIT_INDEXING=ON \
          -DSP_ENABLE_AVX2=ON \
          -DSP_ENABLE_IOMP=OFF \
          -DSP_ENABLE_MKL=ON \
          -DSP_ENABLE_MPI=ON \
          -DSP_ENABLE_SHARED_MKL=OFF \
          -DSP_ENABLE_VTK=ON \
          -DVTK_PATH=/home/runner/work/suanPan/suanPan/lib/cmake/vtk-9.6/
          cmake --build build --target install --config RelWithDebInfo -j $(nproc)
          cmake --build build --target package
      - name: Pack
        run: |
          ./Script/linux-patcher.sh ./build/dist/bin/suanPan
          cp updater build/dist/bin
          file_name="suanPan-linux-amd64-release-gcc-avx-vtk-mkl-mpi.tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT }}
          path: build/dist
  macos-dev:
    if: ${{ !contains(github.event.head_commit.message, '[skip.macos]') && !contains(github.event.head_commit.message, '[skip.all]') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14-large, macos-14-xlarge]
        build: [RelWithDebInfo]
        compiler: [gcc, clang]
        vtk: [ON, OFF]
        exclude:
          - compiler: gcc
            vtk: ON
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Compile
        run: |
          brew install glfw glew go libomp
          go build Checker/updater.go
          ./Script/mac-dependency.sh ${{ matrix.os }}
          export FC=gfortran-13
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            if [[ "${{ matrix.os }}" == "macos-26-large" || "${{ matrix.os }}" == "macos-26-xlarge" ]]; then
              export CC=$(brew --prefix llvm@20)/bin/clang
              export CXX=$(brew --prefix llvm@20)/bin/clang++
            elif [[ "${{ matrix.os }}" == "macos-15-large" || "${{ matrix.os }}" == "macos-15-xlarge" ]]; then
              export CC=$(brew --prefix llvm@18)/bin/clang
              export CXX=$(brew --prefix llvm@18)/bin/clang++
            else
              export CC=$(brew --prefix llvm@15)/bin/clang
              export CXX=$(brew --prefix llvm@15)/bin/clang++
            fi
            cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DCMAKE_PREFIX_PATH="$(brew --prefix libomp);$(brew --prefix gcc@13)" \
            -DCMAKE_INSTALL_PREFIX=build/dist \
            -DSP_ENABLE_VTK=${{ matrix.vtk }} \
            -DVTK_PATH=/Users/runner/work/suanPan/suanPan/VTK/lib/cmake/vtk-9.6/
          else
            export CC=gcc-13
            export CXX=g++-13
            cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DCMAKE_PREFIX_PATH="$(brew --prefix gcc@13)" \
            -DCMAKE_INSTALL_PREFIX=build/dist \
            -DSP_ENABLE_VTK=${{ matrix.vtk }} \
            -DVTK_PATH=/Users/runner/work/suanPan/suanPan/VTK/lib/cmake/vtk-9.6/
          fi
          cmake --build build --target install --config ${{ matrix.build }} -j 3
      - name: Pack
        run: |
          cp updater build/dist/bin
          ./Script/mac-patcher.sh build/dist
          file_name="suanPan-${{ matrix.os }}"
          file_name="${file_name//xlarge/arm64}"
          file_name="${file_name//large/amd64}"
          file_name+=$([[ "${{ matrix.build }}" == "Debug" ]] && echo "-debug" || echo "-release")
          file_name+="-${{ matrix.compiler }}"
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          [[ "${{ matrix.os }}" != *"xlarge"* ]] && file_name+="-avx"
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
      - name: Test
        run: ./build/dist/bin/suanPan -v
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT }}
          path: build/dist
  windows-dev:
    if: ${{ !contains(github.event.head_commit.message, '[skip.windows.vs]') && !contains(github.event.head_commit.message, '[skip.windows]') && !contains(github.event.head_commit.message, '[skip.all]') }}
    runs-on: windows-2025
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        build: [Release]
        compiler: ["Visual Studio 17 2022"]
        vtk: [ON, OFF]
        avx: [OFF]
        mkl: [OFF]
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: MKL
        shell: cmd
        if: matrix.mkl == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ae472ff5-aa01-4a72-a452-ce7b559ef041/intel-onemkl-2025.3.1.10_offline.exe
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/039121f2-d488-4bc1-a5bb-97528e3a4b86/intel-fortran-compiler-2025.3.2.26_offline.exe
          intel-onemkl-2025.3.1.10_offline.exe -s -a --silent --eula accept
          intel-fortran-compiler-2025.3.2.26_offline.exe -s -a --silent --eula accept
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.1-win.7z
          7z x VTK-9.6.1-win.7z
      - name: Compile
        run: |
          go build Checker/updater.go
          if (Test-Path "C:/Program Files (x86)/Intel/oneAPI/") {
            cmd.exe "/K" '"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" && powershell'
          }
          cmake -G "${{ matrix.compiler }}" -T fortran=ifx -S . -B build `
          -DCMAKE_BUILD_TYPE=${{ matrix.build }} `
          -DCMAKE_INSTALL_PREFIX=build/dist `
          -DSP_ENABLE_AVX2=${{ matrix.avx }} `
          -DSP_ENABLE_MKL=${{ matrix.mkl }} `
          -DSP_ENABLE_SHARED_MKL=OFF `
          -DSP_ENABLE_VTK=${{ matrix.vtk }} `
          -DVTK_PATH=D:/a/suanPan/suanPan/lib/cmake/vtk-9.6/
          cmake --build build --target install --config ${{ matrix.build }} -j 4
          cp ./updater.exe build/dist/bin
      - name: Pack
        shell: bash
        run: |
          file_name="suanPan-win"
          file_name+=$([[ "${{ matrix.build }}" == "Debug" ]] && echo "-debug" || echo "-release")
          file_name+=$([[ "${{ matrix.mkl }}" == "ON" ]] && echo "-mkl" || echo "-openblas")
          file_name+=$([[ "${{ matrix.avx }}" == "ON" ]] && echo "-avx" || echo "-no-avx")
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          file_name+=".zip"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          ./Script/win-patcher.sh build/dist/bin/suanPan.exe
          ./build/dist/bin/suanPan.exe -v
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT }}
          path: build/dist/bin
  windows-gcc-dev:
    if: ${{ !contains(github.event.head_commit.message, '[skip.windows.gcc]') && !contains(github.event.head_commit.message, '[skip.windows]') && !contains(github.event.head_commit.message, '[skip.all]') }}
    runs-on: windows-2025
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        build: [Release]
        compiler: ["MinGW Makefiles"]
        vtk: [ON]
        avx: [OFF]
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: GCC
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.3.0posix-11.0.1-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.3.0-mingw-w64ucrt-11.0.1-r1.7z
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.1-win-gcc.7z
          7z x VTK-9.6.1-win-gcc.7z -oVTK
      - name: Compile
        run: |
          go build Checker/updater.go
          cmake -G "${{ matrix.compiler }}" -S . -B build `
          -DCMAKE_BUILD_TYPE=${{ matrix.build }} `
          -DCMAKE_C_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gcc.exe `
          -DCMAKE_CXX_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/g++.exe `
          -DCMAKE_Fortran_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gfortran.exe `
          -DCMAKE_INSTALL_PREFIX=build/dist `
          -DSP_ENABLE_AVX2=${{ matrix.avx }} `
          -DSP_ENABLE_VTK=${{ matrix.vtk }} `
          -DVTK_PATH=D:/a/suanPan/suanPan/VTK/lib/cmake/vtk-9.6
          cmake --build build --target install --config ${{ matrix.build }} -j 4
          cp ./updater.exe build/dist/bin
      - name: Pack
        shell: bash
        run: |
          file_name="suanPan-win-gcc"
          file_name+=$([[ "${{ matrix.build }}" == "Debug" ]] && echo "-debug" || echo "-release")
          file_name+="-openblas"
          file_name+=$([[ "${{ matrix.avx }}" == "ON" ]] && echo "-avx" || echo "-no-avx")
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          file_name+=".zip"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          ./Script/win-patcher.sh build/dist/bin/suanPan.exe
          ./build/dist/bin/suanPan.exe -v
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT }}
          path: build/dist/bin
