name: Dev
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  ubuntu-dev:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Golang
        uses: actions/setup-go@v3
      - name: Compile
        run: |
          go build Checker/updater.go
          mkdir cmake-build-debug && cd cmake-build-debug
          cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=ON -DUSE_HDF5=ON ../
          make -j"$(nproc)"
          chmod +x ../Script/Coverage.sh
          ../Script/Coverage.sh .
          for SRC in `find . | egrep '\.o'`; do gcov -n $SRC > /dev/null; done
          cd ..
      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          gcov: true
  macos-dev:
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Golang
        uses: actions/setup-go@v3
      - name: Compile
        run: |
          export CC=gcc-11 && export CXX=g++-11 && export FC=gfortran-11
          go build Checker/updater.go
          brew install libomp
          cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_HDF5=ON .
          make -j4
          export DYLD_LIBRARY_PATH=Libs/mac/
          ./suanPan -v
