name: Docker Base Image
on:
  schedule:
    - cron: '0 5 2 * *'
jobs:
  env-image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx
        uses: docker/setup-buildx-action@v3
      - name: Base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Script/Rocky.Pre.Dockerfile
          push: true
          tags: tlcfem/suanpan-env:latest
      - name: CUDA
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Script/Rocky.Pre.CUDA.Dockerfile
          push: true
          tags: tlcfem/suanpan-env-cuda:latest
