concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  ARTIFACT: ''
  SP_TIME: ''
jobs:
  guard:
    if: github.repository == 'TLCFEM/suanPan'
    runs-on: ubuntu-slim
    steps:
      - run: echo "Hello, World!"
  linux-master:
    needs: guard
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - if: matrix.mkl == 'ON'
        name: MKL
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mkl-devel
      - name: Compile
        run: |
          sudo apt-get update && sudo apt-get install libglvnd-dev dpkg-dev xz-utils patchelf
          go build Checker/updater.go
          ./Script/linux-dependency.sh ${{ matrix.os }}
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=build/dist \
          -DSP_BUILD_PARALLEL=ON \
          -DSP_ENABLE_AOCL=${{ matrix.aocl }} \
          -DSP_ENABLE_ARMA_SMALL_MEMORY=OFF \
          -DSP_ENABLE_AVX2=${{ matrix.avx }} \
          -DSP_ENABLE_IOMP=OFF \
          -DSP_ENABLE_MKL=${{ matrix.mkl }} \
          -DSP_ENABLE_SHARED_MKL=OFF \
          -DSP_ENABLE_VTK=${{ matrix.vtk }} \
          -DVTK_PATH=/home/runner/work/suanPan/suanPan/VTK/lib/cmake/vtk-9.6/
          cmake --build build --target install --config Release -j $(nproc)
          cmake --build build --target package
          ./Script/linux-patcher.sh ./build/dist/bin/suanPan
          cp updater build/dist/bin
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.4.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-linux"
          file_name+=$([[ "${{ matrix.os }}" != *"arm"* ]] && echo "-amd64" || echo "-arm64")
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            file_name+="-mkl"
          elif [ "${{ matrix.aocl }}" == "ON" ]; then
            file_name+="-aocl"
          else
            file_name+="-openblas"
          fi
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          if [[ "${{ matrix.os }}" != *"arm"* ]]; then
            file_name+=$([[ "${{ matrix.avx }}" == "ON" ]] && echo "-avx" || echo "-no-avx")
          fi
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ env.ARTIFACT }}
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: ${{ env.ARTIFACT }}
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
    strategy:
      fail-fast: false
      matrix:
        aocl:
          - 'ON'
          - 'OFF'
        avx:
          - 'ON'
          - 'OFF'
        exclude:
          - aocl: 'ON'
            mkl: 'ON'
          - avx: 'ON'
            os: ubuntu-24.04-arm
          - mkl: 'ON'
            os: ubuntu-24.04-arm
          - aocl: 'ON'
            os: ubuntu-24.04-arm
        mkl:
          - 'ON'
          - 'OFF'
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        vtk:
          - 'ON'
          - 'OFF'
    timeout-minutes: 60
  linux-master-mpi:
    needs: guard
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - name: VTK
        run: |
          wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.2-${{ matrix.os }}.tar.gz && tar xf VTK-9.6.2-${{ matrix.os }}.tar.gz
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mkl-devel intel-oneapi-mpi-devel libglvnd-dev dpkg-dev xz-utils patchelf
      - name: Compile
        run: |
          go build Checker/updater.go
          source /opt/intel/oneapi/setvars.sh
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=build/dist \
          -DSP_BUILD_PARALLEL=ON \
          -DSP_ENABLE_64BIT_INDEXING=ON \
          -DSP_ENABLE_AVX2=OFF \
          -DSP_ENABLE_IOMP=OFF \
          -DSP_ENABLE_MKL=ON \
          -DSP_ENABLE_MPI=ON \
          -DSP_ENABLE_SHARED_MKL=OFF \
          -DSP_ENABLE_VTK=ON \
          -DVTK_PATH=/home/runner/work/suanPan/suanPan/lib/cmake/vtk-9.6/
          cmake --build build --target install --config Release -j $(nproc)
          cmake --build build --target package
          ./Script/linux-patcher.sh ./build/dist/bin/suanPan
          cp updater build/dist/bin
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.4.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-linux-amd64-mkl-vtk-mpi-no-avx-ilp64.tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ env.ARTIFACT }}
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: ${{ env.ARTIFACT }}
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    timeout-minutes: 60
  macos-master:
    needs: guard
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - name: Compile
        run: |
          brew install glfw glew go libomp
          go build Checker/updater.go
          ./Script/mac-dependency.sh ${{ matrix.os }}
          if [[ "${{ matrix.os }}" == "macos-26-large" || "${{ matrix.os }}" == "macos-26-xlarge" ]]; then
            export CC=$(brew --prefix llvm@20)/bin/clang
            export CXX=$(brew --prefix llvm@20)/bin/clang++
          elif [[ "${{ matrix.os }}" == "macos-15-large" || "${{ matrix.os }}" == "macos-15-xlarge" ]]; then
            export CC=$(brew --prefix llvm@18)/bin/clang
            export CXX=$(brew --prefix llvm@18)/bin/clang++
          else
            export CC=$(brew --prefix llvm@15)/bin/clang
            export CXX=$(brew --prefix llvm@15)/bin/clang++
          fi
          export FC=gfortran-15
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include \
          -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include \
          -DCMAKE_Fortran_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include \
          -DCMAKE_PREFIX_PATH="$(brew --prefix libomp);$(brew --prefix gcc@13)" \
          -DCMAKE_INSTALL_PREFIX=build/dist \
          -DSP_BUILD_PARALLEL=ON \
          -DSP_ENABLE_VTK=${{ matrix.vtk }} \
          -DVTK_PATH=/Users/runner/work/suanPan/suanPan/VTK/lib/cmake/vtk-9.6/
          cmake --build build --target install --config Release -j 3
          cp updater build/dist/bin
          ./Script/mac-patcher.sh build/dist
      - name: Cosign
        uses: sigstore/gh-action-sigstore-python@v3.4.0
        with:
          inputs: build/dist/bin/*
      - name: Pack
        run: |
          file_name="suanPan-${{ matrix.os }}-openblas"
          file_name="${file_name//xlarge/arm64}"
          file_name="${file_name//large/amd64}"
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          [[ "${{ matrix.os }}" != *"xlarge"* ]] && file_name+="-avx"
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ env.ARTIFACT }}
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: ${{ env.ARTIFACT }}
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-large
          - macos-15-large
          - macos-15-xlarge
          - macos-15-xlarge
        vtk:
          - 'ON'
    timeout-minutes: 100
  virustotal-scan:
    needs:
      - linux-master
      - linux-master-mpi
      - macos-master
      - windows-master
      - windows-gcc-master
    runs-on: ubuntu-slim
    steps:
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - name: VirusTotal
        uses: cssnr/virustotal-action@v2
        with:
          release_heading: '### 🛡️ VirusTotal Results'
          release_id: ${{ env.SP_TIME }}
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
  windows-gcc-master:
    needs: guard
    runs-on: windows-2025
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: Prepare
        run: |
          echo ("SP_TIME=daily-"+(get-date -format "yyMMdd")) >> $env:GITHUB_ENV
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/15.3.0posix-14.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-15.3.0-mingw-w64ucrt-14.0.0-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-15.3.0-mingw-w64ucrt-14.0.0-r1.7z
      - if: matrix.vtk == 'ON'
        name: VTK
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.2-win-gcc.7z
          7z x VTK-9.6.2-win-gcc.7z -oVTK
      - name: Compile
        run: |
          go build Checker/updater.go
          cmake -G "MinGW Makefiles" -S . -B build `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_C_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gcc.exe `
          -DCMAKE_CXX_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/g++.exe `
          -DCMAKE_Fortran_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gfortran.exe `
          -DCMAKE_INSTALL_PREFIX=build/dist `
          -DSP_BUILD_PARALLEL=ON `
          -DSP_ENABLE_AVX2=${{ matrix.avx }} `
          -DSP_ENABLE_VTK=${{ matrix.vtk }} `
          -DVTK_PATH=D:/a/suanPan/suanPan/VTK/lib/cmake/vtk-9.6
          cmake --build build --target install --config Release -j 4
          cp ./updater.exe build/dist/bin
      - name: Name
        run: |
          file_name="suanPan-win-gcc-openblas"
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          [[ "${{ matrix.avx }}" == "OFF" ]] && file_name+="-no-avx"
          file_name+=".zip"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          ./Script/win-patcher.sh build/dist/bin/suanPan.exe
        shell: bash
      - id: upload-unsigned-gcc
        if: ${{ github.event_name == 'push' }}
        name: Unsigned
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-${{ env.ARTIFACT }}
          path: build/dist/bin/*.exe
      - if: ${{ github.event_name == 'push' }}
        name: Sign
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH }}
          github-artifact-id: ${{ steps.upload-unsigned-gcc.outputs.artifact-id }}
          organization-id: b04bac88-d6e9-4140-948d-cb95e3095cbe
          output-artifact-directory: build/dist/bin
          project-slug: suanPan
          signing-policy-slug: release-signing
          wait-for-completion: true
      - name: Pack
        run: |
          cd build/dist/bin
          7z a -tzip ../../../${{ env.ARTIFACT }} ./*
        shell: bash
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ env.ARTIFACT }}
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: ${{ env.ARTIFACT }}
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
    strategy:
      fail-fast: false
      matrix:
        avx:
          - 'ON'
          - 'OFF'
        vtk:
          - 'ON'
    timeout-minutes: 120
  windows-master:
    needs: guard
    runs-on: windows-2025
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Golang
        uses: actions/setup-go@v6
        with:
          cache: false
      - name: Prepare
        run: |
          echo ("SP_TIME=daily-"+(get-date -format "yyMMdd")) >> $env:GITHUB_ENV
      - if: matrix.mkl == 'ON'
        name: MKL
        run: |
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/90d3404b-65cf-426d-8484-71e129454dba/intel-onemkl-2026.0.0.907_offline.exe
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/9af38d13-867b-45af-a950-0b42d9bac1ae/intel-fortran-compiler-2026.0.0.566_offline.exe
          intel-onemkl-2026.0.0.907_offline.exe -s -a --silent --eula accept
          intel-fortran-compiler-2026.0.0.566_offline.exe -s -a --silent --eula accept
        shell: cmd
      - if: matrix.vtk == 'ON'
        name: VTK
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.6.2-win.7z
          7z x VTK-9.6.2-win.7z
      - name: Compile
        run: |
          go build Checker/updater.go
          if (Test-Path "C:/Program Files (x86)/Intel/oneAPI/") {
            cmd.exe "/K" '"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" && powershell'
          }
          cmake -T fortran=ifx -S . -B build `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX=build/dist `
          -DSP_BUILD_PARALLEL=ON `
          -DSP_ENABLE_AVX2=${{ matrix.avx }} `
          -DSP_ENABLE_MKL=${{ matrix.mkl }} `
          -DSP_ENABLE_SHARED_MKL=OFF `
          -DSP_ENABLE_VTK=${{ matrix.vtk }} `
          -DVTK_PATH=D:/a/suanPan/suanPan/lib/cmake/vtk-9.6/
          cmake --build build --target install --config Release -j 4
          cp ./updater.exe build/dist/bin
      - name: Name
        run: |
          file_name="suanPan-win"
          file_name+=$([[ "${{ matrix.mkl }}" == "ON" ]] && echo "-mkl" || echo "-openblas")
          [[ "${{ matrix.vtk }}" == "ON" ]] && file_name+="-vtk"
          [[ "${{ matrix.avx }}" == "OFF" ]] && file_name+="-no-avx"
          file_name+=".zip"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          ./Script/win-patcher.sh build/dist/bin/suanPan.exe
        shell: bash
      - id: upload-unsigned-vs
        if: ${{ github.event_name == 'push' }}
        name: Unsigned
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-${{ env.ARTIFACT }}
          path: build/dist/bin/*.exe
      - if: ${{ github.event_name == 'push' }}
        name: Sign
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH }}
          github-artifact-id: ${{ steps.upload-unsigned-vs.outputs.artifact-id }}
          organization-id: b04bac88-d6e9-4140-948d-cb95e3095cbe
          output-artifact-directory: build/dist/bin
          project-slug: suanPan
          signing-policy-slug: release-signing
          wait-for-completion: true
      - name: Pack
        run: |
          cd build/dist/bin
          7z a -tzip ../../../${{ env.ARTIFACT }} ./*
        shell: bash
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ env.ARTIFACT }}
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: ${{ env.ARTIFACT }}
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
      - if: matrix.mkl == 'ON' && matrix.vtk == 'ON' && matrix.avx == 'ON'
        name: CHOCO
        run: |
          python Enhancement/suanPan.py build/dist/bin
          ls -halt
          if [ "${{ github.event_name }}" == "push" ]; then
            choco apikey --key ${{ secrets.CHOCO_KEY }} --source https://push.chocolatey.org/
            choco push suanpan.4.2.0.nupkg --source https://push.chocolatey.org/
          fi
        shell: bash
      - if: matrix.mkl == 'ON' && matrix.vtk == 'ON' && matrix.avx == 'ON'
        name: Release SHA256
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: suanPan-win-mkl-vtk.sha256
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: suanPan-win-mkl-vtk.sha256
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
      - if: matrix.mkl == 'ON' && matrix.vtk == 'ON' && matrix.avx == 'ON'
        name: Release NUPKG
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: suanpan.4.2.0.nupkg
          body: |
            This release is automatically generated by CI/CD pipelines.
          file: suanpan.4.2.0.nupkg
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SP_TIME }}
    strategy:
      fail-fast: false
      matrix:
        avx:
          - 'ON'
          - 'OFF'
        mkl:
          - 'ON'
        vtk:
          - 'ON'
    timeout-minutes: 120
name: Stable
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: write
  id-token: write
