name: Release With MKL VTK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linux-mkl-vtk:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install MKL VTK
        run: |
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          wget https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.1.0-linux.tar.gz
          tar xf VTK-9.1.0-linux.tar.gz
      - name: Golang
        uses: actions/setup-go@v2
      - name: Compile
        run: |
          export CC=gcc-10 && export CXX=g++-10 && export FC=gfortran-10
          go build Checker/updater.go
          sudo apt-get update && sudo apt-get install mesa-common-dev mesa-utils freeglut3-dev libglvnd-dev intel-oneapi-mkl-devel
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./lib/cmake/vtk-9.1/ -DUSE_MKL=ON -DMKLROOT=/opt/intel/oneapi/mkl/latest/ -DUSE_INTEL_OPENMP=OFF -DLINK_DYNAMIC_MKL=OFF -DCMAKE_INSTALL_PREFIX=suanPan-linux-mkl-vtk .
          make install -j4
      - name: Pack
        run: |
          cp updater suanPan-linux-mkl-vtk/bin
          tar czf suanPan-linux-mkl-vtk.tar.gz suanPan-linux-mkl-vtk
          rm suanPan-linux-mkl-vtk/bin/updater
          rm suanPan-linux-mkl-vtk/bin/CHANGELOG.md
          rm suanPan-linux-mkl-vtk/bin/LICENSE
          rm suanPan-linux-mkl-vtk/bin/README.md
          mkdir suanpan_2.3_amd64 && cd suanpan_2.3_amd64
          mkdir -p usr/local/bin
          mkdir -p usr/lib
          cp -r ../suanPan-linux-mkl-vtk/bin/* usr/local/bin
          cp -r ../suanPan-linux-mkl-vtk/lib/* usr/lib
          mkdir DEBIAN
          tee > DEBIAN/control << EOF
          Package: suanpan
          Version: 2.3
          Architecture: amd64
          Maintainer: Theodore Chang <tlcfem@gmail.com>
          Description: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework.
          Depends: libgfortran5, libgomp1, libglx0
          EOF
          cd ..
          dpkg-deb --build --root-owner-group suanpan_2.3_amd64
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/suanPan-linux-mkl-vtk/lib
          cd suanPan-linux-mkl-vtk/bin
          ./suanPan -v
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-linux-mkl-vtk.tar.gz
          asset_name: suanPan-linux-mkl-vtk.tar.gz
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
      - name: DEB
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanpan_2.3_amd64.deb
          asset_name: suanpan_2.3_amd64.deb
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
