name: Release With MKL VTK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu-mkl-vtk:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Install MKL VTK
        run: |
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          wget https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-linux.tar.gz
          tar xf VTK-9.2.6-linux.tar.gz
      - name: Golang
        uses: actions/setup-go@v3
      - name: Compile
        run: |
          go build Checker/updater.go
          sudo apt-get update && sudo apt-get install mesa-common-dev mesa-utils freeglut3-dev libglvnd-dev intel-oneapi-mkl-devel dpkg-dev
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./lib/cmake/vtk-9.2/ -DUSE_MKL=ON -DMKLROOT=/opt/intel/oneapi/mkl/latest/ -DUSE_INTEL_OPENMP=OFF -DLINK_DYNAMIC_MKL=OFF -DCMAKE_INSTALL_PREFIX=suanPan-linux-mkl-vtk .
          make install -j"$(nproc)"
          make package
      - name: Pack
        run: |
          cp updater suanPan-linux-mkl-vtk/bin
          tar czf suanPan-linux-mkl-vtk.tar.gz suanPan-linux-mkl-vtk
      - name: Test
        run: |
          sudo apt-get install ./suanPan-3.1.0-1.x86_64.deb -y
          suanPan -v
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/suanPan-linux-mkl-vtk/lib
          cd suanPan-linux-mkl-vtk/bin
          ./suanPan -v
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-linux-mkl-vtk.tar.gz
          asset_name: suanPan-linux-mkl-vtk.tar.gz
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
      - name: DEB
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-3.1.0-1.x86_64.deb
          asset_name: suanPan-3.1.0-1.x86_64.deb
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
  ubuntu-mkl-vtk-no-avx:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Install MKL VTK
        run: |
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          wget https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-linux.tar.gz
          tar xf VTK-9.2.6-linux.tar.gz
      - name: Golang
        uses: actions/setup-go@v3
      - name: Compile
        run: |
          go build Checker/updater.go
          sudo apt-get update && sudo apt-get install mesa-common-dev mesa-utils freeglut3-dev libglvnd-dev intel-oneapi-mkl-devel dpkg-dev
          cmake -DCMAKE_BUILD_TYPE=Release -DUSE_AVX=OFF -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./lib/cmake/vtk-9.2/ -DUSE_MKL=ON -DMKLROOT=/opt/intel/oneapi/mkl/latest/ -DUSE_INTEL_OPENMP=OFF -DLINK_DYNAMIC_MKL=OFF -DCMAKE_INSTALL_PREFIX=suanPan-linux-mkl-vtk-no-avx .
          make install -j"$(nproc)"
          make package
      - name: Pack
        run: |
          cp updater suanPan-linux-mkl-vtk-no-avx/bin
          tar czf suanPan-linux-mkl-vtk-no-avx.tar.gz suanPan-linux-mkl-vtk-no-avx
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-linux-mkl-vtk-no-avx.tar.gz
          asset_name: suanPan-linux-mkl-vtk-no-avx.tar.gz
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
  fedora-mkl-vtk:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    container: fedora:36
    steps:
      - name: Setup
        run: |
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          tee > oneAPI.repo << EOF
          [oneAPI]
          name=Intel oneAPI repository
          baseurl=https://yum.repos.intel.com/oneapi
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          EOF
          mv oneAPI.repo /etc/yum.repos.d/
          dnf upgrade --refresh -y
          dnf install libglvnd-devel gcc g++ gfortran rpm-build rpm-devel rpmdevtools cmake wget intel-oneapi-mkl-devel git -y
          git config --global --add safe.directory /__w/suanPan/suanPan
      - name: Clone
        uses: actions/checkout@v3
      - name: Install MKL VTK
        run: |
          wget https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-linux.tar.gz
          tar xf VTK-9.2.6-linux.tar.gz
      - name: Compile
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./lib/cmake/vtk-9.2/ -DUSE_MKL=ON -DMKLROOT=/opt/intel/oneapi/mkl/latest/ -DUSE_INTEL_OPENMP=OFF -DLINK_DYNAMIC_MKL=OFF .
          make package -j"$(nproc)"
      - name: Test
        run: |
          dnf install ./suanPan-3.1.0-1.x86_64.rpm -y
          suanPan -v
      - name: RPM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-3.1.0-1.x86_64.rpm
          asset_name: suanPan-3.1.0-1.x86_64.rpm
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
