name: Stable
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu-master:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        avx: [ ON, OFF ]
        vtk: [ ON, OFF ]
        mkl: [ ON, OFF ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Golang
        uses: actions/setup-go@v5
        with:
          cache: false
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-linux.tar.gz
          tar xf VTK-9.2.6-linux.tar.gz
      - name: MKL
        if: matrix.mkl == 'ON'
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mkl-devel
      - name: Dependency
        run: |
          sudo apt-get update && sudo apt-get install mesa-common-dev mesa-utils freeglut3-dev libglvnd-dev dpkg-dev xz-utils
      - name: Compile
        run: |
          go build Checker/updater.go
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DUSE_AVX2=${{ matrix.avx }} -DBUILD_MULTITHREAD=ON -DUSE_VTK=${{ matrix.vtk }} -DVTK_DIR=/home/runner/work/suanPan/suanPan/lib/cmake/vtk-9.2/ -DUSE_MKL=${{ matrix.mkl }} -DMKLROOT=/opt/intel/oneapi/mkl/latest/ -DLINK_DYNAMIC_MKL=OFF -DUSE_INTEL_OPENMP=OFF -DCMAKE_INSTALL_PREFIX=dist ..
          make install -j"$(nproc)" && make package
      - name: Pack
        run: |
          cp updater build/dist/bin
          file_name="suanPan-linux"
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            file_name+="-mkl"
          else
            file_name+="-openblas"
          fi
          if [ "${{ matrix.vtk }}" == "ON" ]; then
            file_name+="-vtk"
          fi
          if [ "${{ matrix.avx }}" == "OFF" ]; then
            file_name+="-no-avx"
          fi
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACT }}
          asset_name: ${{ env.ARTIFACT }}
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
          body: |
            This release is automatically generated by CI/CD pipelines.
  macos-master:
    runs-on: macos-13
    timeout-minutes: 100
    strategy:
      matrix:
        vtk: [ ON, OFF ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          echo "SP_TIME=daily-$(date +''%y%m%d'')" >> $GITHUB_ENV
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-macos.tar.gz
          tar xf VTK-9.2.6-macos.tar.gz
          brew install glfw glew
      - name: Compile
        run: |
          brew install go libomp
          go build Checker/updater.go
          mkdir build && cd build
          export CC=$(brew --prefix llvm@15)/bin/clang
          export CXX=$(brew --prefix llvm@15)/bin/clang++
          export FC=gfortran-12
          export CXXFLAGS="-Wl,-ld_classic"
          cmake -DCMAKE_C_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include -DCMAKE_Fortran_STANDARD_INCLUDE_DIRECTORIES=$(brew --prefix libomp)/include -DCMAKE_BUILD_TYPE=Release -DUSE_VTK=${{ matrix.vtk }} -DBUILD_MULTITHREAD=ON -DVTK_DIR=/Users/runner/work/suanPan/suanPan/lib/cmake/vtk-9.2/ -DCMAKE_INSTALL_PREFIX=dist ..
          make install -j4
      - name: Pack
        run: |
          cp updater build/dist/bin
          file_name="suanPan-macos-openblas"
          if [ "${{ matrix.vtk }}" == "ON" ]; then
            file_name+="-vtk"
          fi
          file_name+=".tar.gz"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          tar czf $file_name -C build/dist .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACT }}
          asset_name: ${{ env.ARTIFACT }}
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
          body: |
            This release is automatically generated by CI/CD pipelines.
  windows-master:
    runs-on: windows-2022
    timeout-minutes: 120
    strategy:
      matrix:
        avx: [ ON, OFF ]
        vtk: [ ON, OFF ]
        mkl: [ ON, OFF ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Golang
        uses: actions/setup-go@v5
        with:
          cache: false
      - name: Prepare
        run: |
          echo ("SP_TIME=daily-"+(get-date -format "yyMMdd")) >> $env:GITHUB_ENV
      - name: MKL
        shell: cmd
        if: matrix.mkl == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/a665fc26-bdf1-415f-9fc4-345f257f4fb1/w_onemkl_p_2024.2.1.106_offline.exe
          C:/msys64/usr/bin/wget.exe -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ea23d696-a77f-4a4a-8996-20d02cdbc48f/w_fortran-compiler_p_2024.2.1.81_offline.exe
          w_onemkl_p_2024.2.1.106_offline.exe -s -a --silent --eula accept
          w_fortran-compiler_p_2024.2.1.81_offline.exe -s -a --silent --eula accept
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.2.6-win.7z
          7z x VTK-9.2.6-win.7z
      - name: Compile
        run: |
          go build Checker/updater.go
          mkdir build && cd build
          if (Test-Path "C:/Program Files (x86)/Intel/oneAPI/") {
            cmd.exe "/K" '"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" && powershell'
          }
          cmake -DCMAKE_BUILD_TYPE=Release -DUSE_AVX2=${{ matrix.avx }} -DBUILD_MULTITHREAD=ON -DUSE_VTK=${{ matrix.vtk }} -DVTK_DIR=D:/a/suanPan/suanPan/lib/cmake/vtk-9.2/ -DUSE_MKL=${{ matrix.mkl }} -DLINK_DYNAMIC_MKL=OFF -DMKLROOT="C:/Program Files (x86)/Intel/oneAPI/mkl/latest" -DCMAKE_INSTALL_PREFIX=dist ..
          cmake --build . --target install --config Release -j 4
      - name: Pack
        shell: bash
        run: |
          cp updater.exe build/dist/bin
          file_name="suanPan-win"
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            file_name+="-mkl"
          else
            file_name+="-openblas"
          fi
          if [ "${{ matrix.vtk }}" == "ON" ]; then
            file_name+="-vtk"
          fi
          if [ "${{ matrix.avx }}" == "OFF" ]; then
            file_name+="-no-avx"
          fi
          if [ "${{ matrix.mkl }}" == "ON" ]; then
            file_name+=".zip"
            echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
            cd build/dist/bin
            7z a -tzip ../../../$file_name ./*
          else
            file_name+=".7z"
            echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
            cd build/dist/bin
            7z a ../../../$file_name ./*
          fi
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACT }}
          asset_name: ${{ env.ARTIFACT }}
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
          body: |
            This release is automatically generated by CI/CD pipelines.
      - name: CHOCO
        if: matrix.mkl == 'ON' && matrix.vtk == 'ON' && matrix.avx == 'ON'
        shell: bash
        run: |
          python Enhancement/pack.ci.py build/dist/bin
          ls -halt
  windows-gcc-master:
    runs-on: windows-2022
    timeout-minutes: 120
    strategy:
      matrix:
        avx: [ ON, OFF ]
        vtk: [ ON, OFF ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Golang
        uses: actions/setup-go@v5
        with:
          cache: false
      - name: Prepare
        run: |
          echo ("SP_TIME=daily-"+(get-date -format "yyMMdd")) >> $env:GITHUB_ENV
          C:/msys64/usr/bin/wget.exe -q https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0posix-18.1.5-11.0.1-msvcrt-r8/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r8.7z
          7z x winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r8.7z
      - name: VTK
        if: matrix.vtk == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -q https://github.com/TLCFEM/prebuilds/releases/download/latest/VTK-9.3.1-win-gcc.7z
          7z x VTK-9.3.1-win-gcc.7z -oVTK
      - name: Compile
        run: |
          go build Checker/updater.go
          mkdir build && cd build
          cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/g++.exe -DCMAKE_Fortran_COMPILER=D:/a/suanPan/suanPan/mingw64/bin/gfortran.exe -DCMAKE_BUILD_TYPE=Release -DUSE_AVX2=${{ matrix.avx }} -DBUILD_MULTITHREAD=ON -DUSE_VTK=${{ matrix.vtk }} -DVTK_DIR=D:/a/suanPan/suanPan/VTK/lib/cmake/vtk-9.3 -DCMAKE_INSTALL_PREFIX=dist ..
          cmake --build . --target install --config Release -j 4
      - name: Pack
        shell: bash
        run: |
          cp updater.exe build/dist/bin
          file_name="suanPan-win-gcc-openblas"
          if [ "${{ matrix.vtk }}" == "ON" ]; then
            file_name+="-vtk"
          fi
          if [ "${{ matrix.avx }}" == "OFF" ]; then
            file_name+="-no-avx"
          fi
          file_name+=".7z"
          echo "ARTIFACT=$file_name" >> "$GITHUB_ENV"
          cd build/dist/bin
          7z a ../../../$file_name ./*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACT }}
          asset_name: ${{ env.ARTIFACT }}
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
          body: |
            This release is automatically generated by CI/CD pipelines.
