name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu-openblas:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Golang
        uses: actions/setup-go@v2
      - name: Compile
        run: |
          go build Checker/updater.go
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DCMAKE_INSTALL_PREFIX=suanPan-linux-openblas .
          make install -j"$(nproc)"
      - name: Pack
        run: |
          cp updater suanPan-linux-openblas/bin
          tar czf suanPan-linux-openblas.tar.gz suanPan-linux-openblas
          export LD_LIBRARY_PATH=/home/runner/work/suanPan/suanPan/suanPan-linux-openblas/lib
          ./suanPan-linux-openblas/bin/suanPan -v
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-linux-openblas.tar.gz
          asset_name: suanPan-linux-openblas.tar.gz
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
  macos-openblas:
    runs-on: macos-11
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Golang
        uses: actions/setup-go@v2
      - name: Compile
        run: |
          export CC=gcc-10 && export CXX=g++-10 && export FC=gfortran-10
          go build Checker/updater.go
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DCMAKE_INSTALL_PREFIX=suanPan-macos-openblas .
          make install -j4
      - name: Pack
        run: |
          cp updater suanPan-macos-openblas/bin
          tar czf suanPan-macos-openblas.tar.gz suanPan-macos-openblas
          export DYLD_LIBRARY_PATH=/Users/runner/work/suanPan/suanPan/suanPan-macos-openblas/lib/
          cd suanPan-macos-openblas/bin
          ./suanPan -v
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-macos-openblas.tar.gz
          asset_name: suanPan-macos-openblas.tar.gz
          tag: ${{ env.SP_TIME }}
          prerelease: true
          overwrite: true
